#!/bin/sh
dir=$(dirname $0)
if [ -f "$dir/substvars" ]
then
  rm "$dir/substvars"
fi

ls -1 $dir/*.changelog | while read pkg
do
  pkgname=$(basename $(echo $pkg | sed -e 's/.changelog//'))
  pkgversion=$(head -n1 "$pkg" | sed -E 's/^.*\((.*)\).*$/\1/')
  echo "${pkgname}:Version=${pkgversion}" >> "$dir/substvars"
done
